on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
    - feature/*

name: My Workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: eekdageek/actions-v2-create-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "My fancy title"
